import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

function mdToHtml(md: string): string {
  return md
    .replace(/^## (.+)$/gm, '</p><h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:32px 0 8px;padding-bottom:8px;border-bottom:2px solid #f3f0ff;">$1</h2><p>')
    .replace(/^### (.+)$/gm, '</p><h3 style="font-size:15px;font-weight:600;color:#374151;margin:20px 0 6px;">$1</h3><p>')
    .replace(/^# (.+)$/gm, '</p><h1 style="font-size:22px;font-weight:700;color:#1a1a2e;margin:0 0 16px;">$1</h1><p>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^[-*] (.+)$/gm, '<li style="margin:4px 0;color:#374151;">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, (m) => `<ul style="margin:8px 0 16px;padding-left:20px;">${m}</ul>`)
    .replace(/\|(.+)\|/g, (row) => {
      const cells = row.split("|").filter(Boolean).map((c) => c.trim());
      const isHeader = row.includes("---");
      if (isHeader) return "";
      const tag = "td";
      return `<tr>${cells.map((c) => `<${tag} style="padding:8px 12px;border:1px solid #e5e7eb;font-size:13px;">${c}</${tag}>`).join("")}</tr>`;
    })
    .replace(/((<tr>[\s\S]*?<\/tr>\n?)+)/g, (m) => `<table style="border-collapse:collapse;width:100%;margin:16px 0;">${m}</table>`)
    .replace(/\n\n+/g, "</p><p>")
    .replace(/\n/g, "<br/>");
}

export async function sendBusinessPlanEmail(
  to: string,
  ideaName: string,
  businessPlan: string
): Promise<void> {
  const body = mdToHtml(businessPlan);
  const slug = ideaName.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 50);

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f8f9fc;font-family:'Helvetica Neue',Arial,sans-serif;">
  <div style="max-width:700px;margin:0 auto;padding:32px 16px;">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#9333ea,#7c3aed);border-radius:16px;padding:28px 32px;margin-bottom:32px;">
      <div style="display:flex;align-items:center;gap:12px;">
        <div style="width:36px;height:36px;background:rgba(255,255,255,0.2);border-radius:8px;display:flex;align-items:center;justify-content:center;font-weight:900;color:white;font-size:18px;">V</div>
        <div>
          <div style="color:white;font-size:18px;font-weight:700;">Validate.ai</div>
          <div style="color:rgba(255,255,255,0.7);font-size:12px;">Business Plan Report</div>
        </div>
      </div>
    </div>

    <!-- Title -->
    <div style="background:white;border-radius:12px;border:1px solid #e8eaf2;padding:24px 28px;margin-bottom:24px;">
      <p style="margin:0 0 4px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.08em;color:#9333ea;">Business Plan</p>
      <h1 style="margin:0;font-size:20px;font-weight:700;color:#1a1a2e;">${ideaName}</h1>
    </div>

    <!-- Body -->
    <div style="background:white;border-radius:12px;border:1px solid #e8eaf2;padding:28px 32px;line-height:1.8;color:#374151;font-size:14px;">
      <p>${body}</p>
    </div>

    <!-- Footer -->
    <div style="text-align:center;margin-top:24px;color:#9ca3af;font-size:11px;">
      Generated by Validate.ai &mdash; AI-powered startup due diligence<br/>
      <a href="https://validate.ai" style="color:#9333ea;text-decoration:none;">validate.ai</a>
    </div>
  </div>
</body>
</html>`;

  const fromEmail = process.env.RESEND_FROM_EMAIL || "onboarding@resend.dev";

  await resend.emails.send({
    from: `Validate.ai <${fromEmail}>`,
    to,
    subject: `Your Business Plan: ${ideaName}`,
    html,
    attachments: [
      {
        filename: `validate-ai-business-plan-${slug}.md`,
        content: Buffer.from(businessPlan).toString("base64"),
      },
    ],
  });
}
