"use client";

import { useState } from "react";
import type { UserInput } from "../lib/schemas/input";
import type { FinalScore } from "../lib/schemas/module";

const INCLUSIONS = [
  "Marketing Strategy — positioning, channels, and budget allocation",
  "Financial Plan — 3-year projections, unit economics, break-even",
  "Go-To-Market Strategy — phased launch plan with success metrics",
  "SWOT Analysis — strengths, weaknesses, opportunities, threats",
  "90-Day Action Plan — prioritized milestones and owners",
  "Executive Summary — investor-ready overview",
];

interface BusinessPlanUpsellProps {
  input: UserInput;
  score: FinalScore;
}

export default function BusinessPlanUpsell({ input, score }: BusinessPlanUpsellProps) {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handlePurchase = async () => {
    if (!email || !email.includes("@")) {
      setError("Please enter a valid email address.");
      return;
    }
    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, input, score }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Checkout failed");
      window.location.href = data.url;
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
      setLoading(false);
    }
  };

  return (
    <div className="rounded-2xl overflow-hidden border border-purple-200"
      style={{ background: "linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)" }}>
      {/* Top banner */}
      <div className="px-6 py-3 flex items-center gap-2"
        style={{ background: "linear-gradient(135deg, #9333ea, #7c3aed)" }}>
        <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
        </svg>
        <span className="text-white text-sm font-semibold">Premium Add-on</span>
      </div>

      <div className="p-6 sm:p-8">
        <div className="flex flex-col sm:flex-row sm:items-start gap-6">
          {/* Left: copy */}
          <div className="flex-1">
            <h2 className="text-xl font-bold text-gray-900 mb-1">Get your full business plan</h2>
            <p className="text-sm text-gray-500 mb-5">
              Generated by Claude AI from your validation report and emailed to you instantly.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-6">
              {INCLUSIONS.map((item, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="w-4 h-4 rounded-full flex-shrink-0 mt-0.5 flex items-center justify-center"
                    style={{ background: "linear-gradient(135deg, #9333ea, #7c3aed)" }}>
                    <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                  </span>
                  <span className="text-xs text-gray-700">{item}</span>
                </div>
              ))}
            </div>

            {/* Email + CTA */}
            <div className="flex gap-2">
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handlePurchase()}
                placeholder="your@email.com"
                className="input-field flex-1"
              />
              <button
                onClick={handlePurchase}
                disabled={loading}
                className="btn-brand flex-shrink-0 px-5 py-2.5 rounded-xl text-white font-semibold text-sm disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none shadow-md shadow-purple-200 whitespace-nowrap"
              >
                {loading ? (
                  <span className="flex items-center gap-1.5">
                    <svg className="animate-spin h-3.5 w-3.5" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Redirecting...
                  </span>
                ) : (
                  "Get Plan — $99"
                )}
              </button>
            </div>
            {error && <p className="text-xs text-red-600 mt-2">{error}</p>}
            <p className="text-xs text-gray-400 mt-2">Secure payment via Stripe. Delivered to your email within minutes.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
