import type { FinalOutput } from "../lib/schemas/module";
import ScoreCard from "./ScoreCard";
import ModuleCard from "./ModuleCard";
import MemoView from "./MemoView";
import BusinessPlanUpsell from "./BusinessPlanUpsell";

interface ResultsViewProps {
  result: FinalOutput;
  onReset: () => void;
}

export default function ResultsView({ result, onReset }: ResultsViewProps) {
  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Validation Report</h1>
          <p className="text-sm text-gray-400 mt-0.5">
            {new Date(result.generated_at).toLocaleString()}
          </p>
        </div>
        <button
          onClick={onReset}
          className="text-sm font-medium text-indigo-600 hover:text-indigo-800 px-4 py-2 rounded-lg bg-indigo-50 hover:bg-indigo-100 transition-colors"
        >
          New idea
        </button>
      </div>

      <ScoreCard score={result.score} ideaName={result.input.idea_name} />

      <div>
        <h2 className="text-base font-semibold text-gray-900 mb-3">
          Module Breakdown
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {result.modules.map((module, i) => (
            <ModuleCard key={i} module={module} />
          ))}
        </div>
      </div>

      <MemoView memo={result.memo} />

      <BusinessPlanUpsell input={result.input as import("../lib/schemas/input").UserInput} score={result.score} />

      <div className="text-xs text-gray-400 text-center pb-8">
        Generated by Validate.ai
      </div>
    </div>
  );
}
